spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/recipes?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: recipesUser
    password: recipesPass
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

server:
  shutdown: graceful
  compression:
    enabled: true

application:
  api-key: 'f359105c-56b4-4268-bf23-c6ba706cfe86'
